2025-03-10T09:31:20.636Z [ERROR]: [POST] /api/auth/signup - Expected double-quoted property name in JSON at position 27 (line 3 column 1)
2025-03-10T09:32:23.176Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:33:06.101Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:33:15.392Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:37:55.735Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:40:13.040Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:40:42.331Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-10T09:55:29.006Z [ERROR]: [POST] /api/auth/signup - 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\routes\auth\auth.controller.ts:26:31

  23 
  24 data.password=await argon.hash(data.password);
  25 
→ 26 await prisma.user.create(
Can't reach database server at `ep-odd-union-a4aq59u0-pooler.us-east-1.aws.neon.tech:5432`

Please make sure your database server is running at `ep-odd-union-a4aq59u0-pooler.us-east-1.aws.neon.tech:5432`.
2025-03-10T09:55:41.460Z [ERROR]: [POST] /api/auth/signup - 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\routes\auth\auth.controller.ts:26:31

  23 
  24 data.password=await argon.hash(data.password);
  25 
→ 26 await prisma.user.create(
Can't reach database server at `ep-odd-union-a4aq59u0-pooler.us-east-1.aws.neon.tech:5432`

Please make sure your database server is running at `ep-odd-union-a4aq59u0-pooler.us-east-1.aws.neon.tech:5432`.
2025-03-11T01:02:40.516Z [ERROR]: [POST] /api/auth/signup - 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\routes\auth\auth.controller.ts:26:31

  23 
  24 data.password=await argon.hash(data.password);
  25 
→ 26 await prisma.user.create(
Can't reach database server at `localhost:3306`

Please make sure your database server is running at `localhost:3306`.
2025-03-11T01:07:56.937Z [ERROR]: [POST] /api/auth/signup - 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\routes\auth\auth.service.ts:26:31

  23 
  24 data.password=await argon.hash(data.password);
  25 
→ 26 await prisma.user.create(
Unique constraint failed on the constraint: `users_email_key`
2025-03-11T01:12:33.202Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-11T01:13:22.544Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-11T02:36:46.737Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-11T02:37:01.813Z [ERROR]: [POST] /api/auth/signup - 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\routes\auth\auth.service.ts:29:44

  26 
  27 const hashedPassword = await argon.hash(data.password);
  28 
→ 29 const user = await prisma.user.create(
Can't reach database server at `localhost:3306`

Please make sure your database server is running at `localhost:3306`.
2025-03-11T02:37:36.387Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-11T02:38:02.357Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-11T02:38:23.410Z [ERROR]: [POST] /api/auth/signin - User not found
2025-03-11T02:48:41.248Z [ERROR]: [POST] /api/auth/signin - Expected double-quoted property name in JSON at position 51 (line 4 column 1)
2025-03-11T02:48:46.192Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-11T02:48:55.127Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-11T02:49:08.854Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-11T02:49:15.011Z [ERROR]: [POST] /api/auth/signin - String must contain at least 8 character(s)
2025-03-11T02:49:20.204Z [ERROR]: [POST] /api/auth/signin - String must contain at least 8 character(s)
2025-03-11T02:49:42.137Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-11T02:49:46.992Z [ERROR]: [POST] /api/auth/signin - Validation failed
2025-03-11T02:49:53.173Z [ERROR]: [POST] /api/auth/signin - Incorrect password
2025-03-11T03:02:10.511Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:02:16.364Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:08:16.376Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:08:20.056Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:08:25.941Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-11T03:08:36.258Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:09:44.136Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:09:49.547Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:10:27.406Z [ERROR]: [POST] /api/auth/signin - Cannot read properties of undefined (reading 'id')
2025-03-11T03:12:03.945Z [ERROR]: [POST] /api/auth/signin - Validation failed
2025-03-13T14:17:48.414Z [ERROR]: [POST] /api/auth/signin - 
Invalid `prisma.user.findFirst()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:10:34

   7     throw new Error("Either id or email must be provided.");
   8 }
   9 
→ 10 return await prisma.user.findFirst(
Can't reach database server at `localhost:3306`

Please make sure your database server is running at `localhost:3306`.
2025-03-13T14:38:08.039Z [ERROR]: [POST] /api/auth/reset-password - User not found
2025-03-13T15:12:04.291Z [ERROR]: [POST] /api/auth/reset-password - Missing credentials for "PLAIN"
2025-03-13T15:48:14.084Z [ERROR]: [POST] /api/auth/update-password - Please verify your otp first
2025-03-13T15:48:19.041Z [ERROR]: [POST] /api/auth/update-password - Please verify your otp first
2025-03-13T15:48:23.328Z [ERROR]: [POST] /api/auth/verify-otp - OTP expired
2025-03-17T23:45:41.043Z [ERROR]: [POST] /api/auth/signup - PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
2025-03-17T23:46:43.616Z [ERROR]: [POST] /api/auth/signup - PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
2025-03-17T23:47:14.873Z [ERROR]: [POST] /api/auth/signup - PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
2025-03-17T23:47:38.546Z [ERROR]: [POST] /api/auth/signup - PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
2025-03-17T23:48:51.046Z [ERROR]: [POST] /api/auth/signup - PrismaClientInitializationError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Authentication failed against database server at `localhost`, the provided database credentials for `root` are not valid.

Please make sure to provide valid database credentials for the database server at `localhost`.
2025-03-18T00:00:39.601Z [ERROR]: [POST] /api/auth/signup - PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
The table `users` does not exist in the current database.
2025-03-18T00:02:09.070Z [ERROR]: [POST] /api/auth/signup - PrismaClientKnownRequestError: 
Invalid `prisma.user.create()` invocation in
C:\Users\misba\OneDrive\Desktop\code\be\substack-clone-api\src\prismaService\user.prisma.ts:24:38

  21 
  22 static async create(user:{ name: string; email: string; password: string }) {
  23     try {
→ 24         return await prisma.user.create(
Unique constraint failed on the constraint: `users_email_key`
2025-03-18T00:02:49.294Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-18T00:15:06.402Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-18T00:22:54.343Z [ERROR]: [POST] /api/auth/signin - Expected ':' after property name in JSON at position 11 (line 3 column 1)
2025-03-18T00:23:10.110Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-18T00:23:30.583Z [ERROR]: [POST] /api/auth/signin - User not found
2025-03-18T00:38:49.556Z [ERROR]: [POST] /api/auth/signin - User not found
2025-03-18T00:39:20.005Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T01:13:03.295Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T17:25:35.913Z [ERROR]: [POST] /api/auth/signin - Missing credentials
2025-03-18T17:26:27.436Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-18T17:27:07.222Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-18T17:30:01.687Z [ERROR]: [POST] /api/auth/verify-otp - Validation failed
2025-03-18T17:30:15.732Z [ERROR]: [POST] /api/auth/verify-otp - OTP not found
2025-03-18T17:33:38.614Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-18T17:34:35.480Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T17:35:12.637Z [ERROR]: [POST] /api/auth/verify-otp - OTP not found
2025-03-18T17:36:33.740Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-18T17:38:54.051Z [ERROR]: [POST] /api/auth/verify-otp - Invalid OTP, please try again
2025-03-18T17:39:05.420Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T17:39:32.269Z [ERROR]: [POST] /api/auth/verify-otp - Validation failed
2025-03-18T17:40:02.463Z [ERROR]: [POST] /api/auth/verify-otp - Invalid OTP, please try again
2025-03-18T17:40:34.097Z [ERROR]: [POST] /api/auth/verify-otp - OTP not found
2025-03-18T17:40:53.342Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T17:41:00.384Z [ERROR]: [POST] /api/auth/signin - Please verify your account
2025-03-18T17:57:00.219Z [ERROR]: [GET] /api/users/2 - AppError: User not found
2025-03-18T17:57:35.059Z [ERROR]: [GET] /api/users/2 - AppError: User not found
2025-03-18T17:57:59.628Z [ERROR]: [GET] /api/users/2 - User not found
2025-03-18T17:59:18.020Z [ERROR]: [GET] /api/users/2 - User not found
2025-03-18T18:06:54.909Z [ERROR]: [GET] /api/users/5ec338d1-3427-462f-b16c-5f738d787c5i8 - User not found
2025-03-18T18:13:11.138Z [ERROR]: [POST] /api/auth/signup - Validation failed
2025-03-18T18:13:24.763Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-18T21:41:31.949Z [ERROR]: [PATCH] /api/users/5ec338d1-3427-462f-b16c-5f738d787c55 - Expected double-quoted property name in JSON at position 32 (line 3 column 1)
2025-03-18T21:41:52.567Z [ERROR]: [POST] /api/auth/signin - User is not verified
2025-03-18T21:43:02.808Z [ERROR]: [POST] /api/auth/verify-otp - OTP not found
2025-03-18T21:43:10.083Z [ERROR]: [POST] /api/auth/verify-otp - OTP not found
2025-03-18T21:47:57.645Z [ERROR]: [POST] /api/auth/signin - User is not verified
2025-03-18T21:48:30.299Z [ERROR]: [POST] /api/auth/signin - User is not verified
2025-03-18T21:49:11.796Z [ERROR]: [POST] /api/auth/signin - User is not verified
2025-03-18T21:54:49.823Z [ERROR]: [PATCH] /api/users/5ec338d1-3427-462f-b16c-5f738d787c55 - cannot update other user
2025-03-21T15:07:04.015Z [ERROR]: [POST] /api/auth/signup - User already exists
2025-03-21T15:27:13.103Z [ERROR]: [POST] /api/auth/signup - User already exists
